### PR TITLE
Make Allauth pages not look gross

### PR DESCRIPTION
**Pull request by Mase3206**
No additional tests necessary, since only the styling was changed.

### CODE REVIEW

**Comment by Mase3206** [comment]
I moved the slideshow code into a separate JS file to clean up out base.html.

**Comment by Mase3206** [comment]
Since you're the styling queen @madisonDavis7, wanna review this? 

Make sure to install from the requirements file, since I added some stuff.

**Comment by Mase3206** [comment]
[As a not-so-savvy computer user, I am confused when the log-in page of websites doesn't look like the rest of the website.](https://trello.com/c/dRjFLkHQ/20-as-a-not-so-savvy-computer-user-i-am-confused-when-the-log-in-page-of-websites-doesnt-look-like-the-rest-of-the-website)

**Review by madisonDavis7 — APPROVED** [review]
looks good

**Comment by Mase3206** [comment]
oh damn, that was fast

**Pull request merged**
